services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: "10897"
      MYSQL_DATABASE: "pdapp_db"
      MYSQL_USER: "pdapp"
      MYSQL_PASSWORD: "10897"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
